### ISSUE TITLE
Illustration of use case

### ISSUE THREAD

**Issue by idea-launch-lab** [AmeyKamat/MEERA#18]
Interesting project! Not a feature, but example application or illustration would be terrific. Did you have a specific application or use case in mind when you began developing MEERA? Thanks.

**Comment by AmeyKamat** [comment]
Hey, thanks for this issue and interest in the project.

This was in the back of my mind since couple of days and yes this kind of illustration is in the work.

Use case that started development on [ProjectJarvis](https://github.com/AmeyKamat/ProjectJarvis) was to be a household assistant. JARVIS was a predecessor of MEERA and is now and archived project. MEERA, however is flexible enough to be modeled for wide range of use cases.
